export const LEAD_STATUS_OPTIONS = [
  "NEW",
  "CONTACTED",
  "INTERESTED",
  "PRODUCT_PITCH",
  "PTP",
  "FOLLOW_UP",
  "MEMBER_BUSY",
  "NOT_REACHABLE",
  "OPT_WITH_COMPETITORS",
  "PENDING",
  "CONVERTED",
  "NOT_INTERESTED",
  "NO_NOT_EXIST",
  "WRONG_NUMBER_FAKE_LEAD",
  "CLOSED",
] as const;

export type LeadStatusOption = (typeof LEAD_STATUS_OPTIONS)[number];

export const LEAD_STATUS_LABELS: Record<string, string> = {
  NEW: "New",
  CONTACTED: "Contacted",
  INTERESTED: "Interested",
  PRODUCT_PITCH: "Product Pitch",
  PTP: "P.T.P",
  FOLLOW_UP: "Follow Up",
  MEMBER_BUSY: "Member Busy",
  NOT_REACHABLE: "Not Reachable / No Busy / Ringing",
  OPT_WITH_COMPETITORS: "Opted with Competitors",
  PENDING: "Pending",
  CONVERTED: "Converted",
  NOT_INTERESTED: "Not Interested",
  NO_NOT_EXIST: "No / Doesn't Exist",
  WRONG_NUMBER_FAKE_LEAD: "Wrong Number / Fake Lead",
  CLOSED: "Closed",
};

export const LEAD_STATUS_STYLES: Record<string, string> = {
  NEW: "bg-blue-100 text-blue-700 border-blue-200",
  CONTACTED: "bg-amber-100 text-amber-700 border-amber-200",
  INTERESTED: "bg-green-100 text-green-700 border-green-200",
  PRODUCT_PITCH: "bg-teal-100 text-teal-700 border-teal-200",
  PTP: "bg-cyan-100 text-cyan-700 border-cyan-200",
  FOLLOW_UP: "bg-amber-100 text-amber-700 border-amber-200",
  MEMBER_BUSY: "bg-yellow-100 text-yellow-700 border-yellow-200",
  NOT_REACHABLE: "bg-orange-100 text-orange-700 border-orange-200",
  OPT_WITH_COMPETITORS: "bg-purple-100 text-purple-700 border-purple-200",
  PENDING: "bg-orange-100 text-orange-700 border-orange-200",
  CONVERTED: "bg-emerald-100 text-emerald-700 border-emerald-200",
  NOT_INTERESTED: "bg-red-100 text-red-700 border-red-200",
  NO_NOT_EXIST: "bg-gray-100 text-gray-700 border-gray-200",
  WRONG_NUMBER_FAKE_LEAD: "bg-gray-100 text-gray-700 border-gray-200",
  CLOSED: "bg-gray-100 text-gray-700 border-gray-200",
};
