// src/config/navigation.ts
import {
  LayoutDashboard,
  Users,
  UserSquare2,
  Contact,
  ClipboardList,
  HeartHandshake,
  CreditCard,
  Settings,
  Handshake,
  CalendarClock,
  Activity,
  PhoneCall,
  Target,
  MessageSquare,
  Network,
  TrendingUp,
  Stethoscope,
  Tag,
  ShieldCheck,
  Clock,
  Search,
  UserCheck,
  History,
  XCircle, BarChart3, Eye,
} from "lucide-react";

import type { Role } from "@/lib/permissions/roles";
import type { LucideIcon } from "lucide-react";

export interface NavItem {
  label: string;
  href: string;
  icon: LucideIcon;
  section: string;
}

export const NAV_CONFIG: Record<Role, NavItem[]> = {
  SUPER_ADMIN: [
    { label: "Dashboard", href: "/dashboard/admin", icon: LayoutDashboard, section: "Overview" },
    { label: "Sales Dashboard", href: "/dashboard/admin/sales", icon: TrendingUp, section: "Overview" },
    { label: "Service Dashboard", href: "/dashboard/admin/service", icon: Stethoscope, section: "Overview" },
    { label: "Workspace", href: "/dashboard/workspace", icon: MessageSquare, section: "Overview" },
    { label: "Profiles", href: "/dashboard/admin/profiles", icon: UserSquare2, section: "Profiles & Leads" },
    { label: "Leads", href: "/dashboard/admin/leads", icon: Contact, section: "Profiles & Leads" },
    { label: "Profile Search", href: "/dashboard/profile-search", icon: Search, section: "Profiles & Leads" },
    { label: "Approvals", href: "/dashboard/admin/profile-approvals", icon: ClipboardList, section: "Profiles & Leads" },
    { label: "Profile Queue", href: "/dashboard/admin/profile-queue", icon: ClipboardList, section: "Profiles & Leads" },
    { label: "Employees", href: "/dashboard/admin/employees", icon: Users, section: "Employees" },
    { label: "Employee Access", href: "/dashboard/admin/employee-access", icon: ShieldCheck, section: "Employees" },
    { label: "Team Hierarchy", href: "/dashboard/admin/team-hierarchy", icon: Network, section: "Employees" },
    { label: "Service Overview", href: "/dashboard/admin/service-overview", icon: HeartHandshake, section: "Service" },
    { label: "Newly Paid Clients", href: "/dashboard/admin/newly-paid-clients", icon: UserCheck, section: "Service" },
    { label: "Ongoing Services", href: "/dashboard/admin/ongoing-services", icon: History, section: "Service" },
    { label: "Expired Clients", href: "/dashboard/admin/expired-clients", icon: XCircle, section: "Service" },
    { label: "Expiring Soon", href: "/dashboard/admin/subscriptions/expiring", icon: CalendarClock, section: "Service" },
    { label: "Work Hours Report", href: "/dashboard/admin/attendance-report", icon: Clock, section: "HR" },
    { label: "Welcome Calls", href: "/dashboard/welcome-calls", icon: PhoneCall, section: "General" },
    { label: "Discounts", href: "/dashboard/discounts", icon: Tag, section: "General" },
  ],
  ADMIN: [
    { label: "Dashboard", href: "/dashboard/admin", icon: LayoutDashboard, section: "Overview" },
    { label: "Sales Dashboard", href: "/dashboard/admin/sales", icon: TrendingUp, section: "Overview" },
    { label: "Service Dashboard", href: "/dashboard/admin/service", icon: Stethoscope, section: "Overview" },
    { label: "Workspace", href: "/dashboard/workspace", icon: MessageSquare, section: "Overview" },
    { label: "Profiles", href: "/dashboard/admin/profiles", icon: UserSquare2, section: "Profiles & Leads" },
    { label: "Leads", href: "/dashboard/admin/leads", icon: Contact, section: "Profiles & Leads" },
    { label: "Sales Targets", href: "/dashboard/admin/sales-targets", icon: Target, section: "Profiles & Leads" },
    { label: "Profile Search", href: "/dashboard/profile-search", icon: Search, section: "Profiles & Leads" },
    { label: "Assignments", href: "/dashboard/admin/assignments", icon: ClipboardList, section: "Profiles & Leads" },
    { label: "Approvals", href: "/dashboard/admin/profile-approvals", icon: ClipboardList, section: "Profiles & Leads" },
    { label: "Profile Queue", href: "/dashboard/admin/profile-queue", icon: ClipboardList, section: "Profiles & Leads" },
    { label: "Employees", href: "/dashboard/admin/employees", icon: Users, section: "Employees" },
    { label: "Employee Access", href: "/dashboard/admin/employee-access", icon: ShieldCheck, section: "Employees" },
    { label: "Team Hierarchy", href: "/dashboard/admin/team-hierarchy", icon: Network, section: "Employees" },
    { label: "Plans", href: "/dashboard/admin/plans", icon: HeartHandshake, section: "Sales & Plans" },
    { label: "Subscriptions", href: "/dashboard/admin/subscriptions", icon: HeartHandshake, section: "Sales & Plans" },
    { label: "Payments", href: "/dashboard/admin/payments", icon: CreditCard, section: "Sales & Plans" },
    { label: "Service Overview", href: "/dashboard/admin/service-overview", icon: HeartHandshake, section: "Service" },
    { label: "Call History", href: "/dashboard/admin/welcome-calls", icon: PhoneCall, section: "Service" },
    { label: "Newly Paid Clients", href: "/dashboard/admin/newly-paid-clients", icon: UserCheck, section: "Service" },
    { label: "Ongoing Services", href: "/dashboard/admin/ongoing-services", icon: History, section: "Service" },
    { label: "Expired Clients", href: "/dashboard/admin/expired-clients", icon: XCircle, section: "Service" },
    { label: "Expiring Soon", href: "/dashboard/admin/subscriptions/expiring", icon: CalendarClock, section: "Service" },
    { label: "Settings", href: "/dashboard/admin/settings", icon: Settings, section: "Admin Tools" },
    { label: "Meetings", href: "/dashboard/admin/meetings", icon: CalendarClock, section: "Admin Tools" },
    { label: "Activity Logs", href: "/dashboard/admin/activity-logs", icon: Activity, section: "Admin Tools" },
    { label: "Lead Analytics", href: "/dashboard/admin/lead-analytics", icon: BarChart3, section: "Admin Tools" },
    { label: "Work Hours Report", href: "/dashboard/admin/attendance-report", icon: Clock, section: "Admin Tools" },
    { label: "Welcome Calls", href: "/dashboard/welcome-calls", icon: PhoneCall, section: "General" },
    { label: "Discounts", href: "/dashboard/discounts", icon: Tag, section: "General" },
  ],
  SALES: [
    { label: "Dashboard", href: "/dashboard/sales", icon: LayoutDashboard, section: "Overview" },
    { label: "Workspace", href: "/dashboard/workspace", icon: MessageSquare, section: "Overview" },
    { label: "My Leads", href: "/dashboard/sales/leads", icon: Handshake, section: "Leads" },
    { label: "Profile Search", href: "/dashboard/profile-search", icon: Search, section: "Leads" },
    { label: "Create Profile", href: "/dashboard/profile-creator", icon: UserSquare2, section: "Leads" },
    { label: "Follow-ups", href: "/dashboard/admin/meetings", icon: CalendarClock, section: "Leads" },
    { label: "Welcome Calls", href: "/dashboard/welcome-calls", icon: PhoneCall, section: "General" },
    { label: "Discounts", href: "/dashboard/discounts", icon: Tag, section: "General" },
  ],
  SALES_TL: [
    { label: "Dashboard", href: "/dashboard/sales", icon: LayoutDashboard, section: "Overview" },
    { label: "Workspace", href: "/dashboard/workspace", icon: MessageSquare, section: "Overview" },
    { label: "My Leads", href: "/dashboard/sales/leads", icon: Handshake, section: "Leads" },
    { label: "Profile Search", href: "/dashboard/profile-search", icon: Search, section: "Leads" },
    { label: "Create Profile", href: "/dashboard/profile-creator", icon: UserSquare2, section: "Leads" },
    { label: "Follow-ups", href: "/dashboard/admin/meetings", icon: CalendarClock, section: "Leads" },
    { label: "Welcome Calls", href: "/dashboard/welcome-calls", icon: PhoneCall, section: "General" },
    { label: "Discounts", href: "/dashboard/discounts", icon: Tag, section: "General" },
  ],
  SALES_MANAGER: [
    { label: "Dashboard", href: "/dashboard/sales", icon: LayoutDashboard, section: "Overview" },
    { label: "Workspace", href: "/dashboard/workspace", icon: MessageSquare, section: "Overview" },
    { label: "My Leads", href: "/dashboard/sales/leads", icon: Handshake, section: "Leads" },
    { label: "Profile Search", href: "/dashboard/profile-search", icon: Search, section: "Leads" },
    { label: "Create Profile", href: "/dashboard/profile-creator", icon: UserSquare2, section: "Leads" },
    { label: "Follow-ups", href: "/dashboard/admin/meetings", icon: CalendarClock, section: "Leads" },
    { label: "Welcome Calls", href: "/dashboard/welcome-calls", icon: PhoneCall, section: "General" },
    { label: "Discounts", href: "/dashboard/discounts", icon: Tag, section: "General" },
  ],
  PROFILE_CREATOR: [
    { label: "Dashboard", href: "/dashboard/profile-creator", icon: LayoutDashboard, section: "Overview" },
    { label: "Workspace", href: "/dashboard/workspace", icon: MessageSquare, section: "Overview" },
    { label: "Profile Search", href: "/dashboard/profile-search", icon: Search, section: "Profiles" },
  ],
  SERVICE: [
    { label: "Dashboard", href: "/dashboard/service", icon: LayoutDashboard, section: "Overview" },
    { label: "Workspace", href: "/dashboard/workspace", icon: MessageSquare, section: "Overview" },
    { label: "Assigned Profiles", href: "/dashboard/service/profiles", icon: UserSquare2, section: "Profiles & Meetings" },
    { label: "Profile Search", href: "/dashboard/profile-search", icon: Search, section: "Profiles & Meetings" },
    { label: "Create Profile", href: "/dashboard/profile-creator", icon: UserSquare2, section: "Profiles & Meetings" },
    { label: "Meetings", href: "/dashboard/service/meetings", icon: CalendarClock, section: "Profiles & Meetings" },
    { label: "Service Status", href: "/dashboard/service/status", icon: Activity, section: "Profiles & Meetings" },
    { label: "Ongoing Services", href: "/dashboard/admin/subscriptions", icon: History, section: "Profiles & Meetings" },
    { label: "Expiring Soon", href: "/dashboard/admin/subscriptions/expiring", icon: CalendarClock, section: "Profiles & Meetings" },
    { label: "Expired Clients", href: "/dashboard/admin/expired-clients", icon: XCircle, section: "Profiles & Meetings" },
    { label: "Welcome Calls", href: "/dashboard/welcome-calls", icon: PhoneCall, section: "Calls" },
    { label: "Discounts", href: "/dashboard/discounts", icon: Tag, section: "General" },
  ],
  SERVICE_TL: [
    { label: "Dashboard", href: "/dashboard/service", icon: LayoutDashboard, section: "Overview" },
    { label: "Workspace", href: "/dashboard/workspace", icon: MessageSquare, section: "Overview" },
    { label: "Assigned Profiles", href: "/dashboard/service/profiles", icon: UserSquare2, section: "Profiles & Meetings" },
    { label: "Profile Search", href: "/dashboard/profile-search", icon: Search, section: "Profiles & Meetings" },
    { label: "Create Profile", href: "/dashboard/profile-creator", icon: UserSquare2, section: "Profiles & Meetings" },
    { label: "Meetings", href: "/dashboard/service/meetings", icon: CalendarClock, section: "Profiles & Meetings" },
    { label: "Service Status", href: "/dashboard/service/status", icon: Activity, section: "Profiles & Meetings" },
    { label: "Ongoing Services", href: "/dashboard/admin/subscriptions", icon: History, section: "Profiles & Meetings" },
    { label: "Expiring Soon", href: "/dashboard/admin/subscriptions/expiring", icon: CalendarClock, section: "Profiles & Meetings" },
    { label: "Expired Clients", href: "/dashboard/admin/expired-clients", icon: XCircle, section: "Profiles & Meetings" },
    { label: "Welcome Calls", href: "/dashboard/welcome-calls", icon: PhoneCall, section: "Calls" },
    { label: "Discounts", href: "/dashboard/discounts", icon: Tag, section: "General" },
  ],
  SERVICE_MANAGER: [
    { label: "Dashboard", href: "/dashboard/service", icon: LayoutDashboard, section: "Overview" },
    { label: "Workspace", href: "/dashboard/workspace", icon: MessageSquare, section: "Overview" },
    { label: "Assigned Profiles", href: "/dashboard/service/profiles", icon: UserSquare2, section: "Profiles & Meetings" },
    { label: "Profile Search", href: "/dashboard/profile-search", icon: Search, section: "Profiles & Meetings" },
    { label: "Create Profile", href: "/dashboard/profile-creator", icon: UserSquare2, section: "Profiles & Meetings" },
    { label: "Meetings", href: "/dashboard/service/meetings", icon: CalendarClock, section: "Profiles & Meetings" },
    { label: "Service Status", href: "/dashboard/service/status", icon: Activity, section: "Profiles & Meetings" },
    { label: "Ongoing Services", href: "/dashboard/admin/subscriptions", icon: History, section: "Profiles & Meetings" },
    { label: "Expiring Soon", href: "/dashboard/admin/subscriptions/expiring", icon: CalendarClock, section: "Profiles & Meetings" },
    { label: "Expired Clients", href: "/dashboard/admin/expired-clients", icon: XCircle, section: "Profiles & Meetings" },
    { label: "Welcome Calls", href: "/dashboard/welcome-calls", icon: PhoneCall, section: "Calls" },
    { label: "Discounts", href: "/dashboard/discounts", icon: Tag, section: "General" },
  ],
  SYSTEM: [],
  SME: [
    { label: "Dashboard", href: "/dashboard/sme", icon: LayoutDashboard, section: "Overview" },
    { label: "Workspace", href: "/dashboard/workspace", icon: MessageSquare, section: "Overview" },
    { label: "Non Connected Clients", href: "/dashboard/admin/non-connected-clients", icon: Eye, section: "Service Quality" },
    { label: "Missed Weekly Shares", href: "/dashboard/admin/missed-weekly-shares", icon: HeartHandshake, section: "Service Quality" },
    { label: "Overdue Welcome Calls", href: "/dashboard/admin/overdue-welcome-calls", icon: PhoneCall, section: "Service Quality" },
    { label: "Profiles", href: "/dashboard/admin/profiles", icon: UserSquare2, section: "Profiles" },
    { label: "Profile Search", href: "/dashboard/profile-search", icon: Search, section: "Profiles" },
  ],
  HR: [
    { label: "Dashboard", href: "/dashboard/hr", icon: LayoutDashboard, section: "Overview" },
    { label: "Workspace", href: "/dashboard/workspace", icon: MessageSquare, section: "Overview" },
    { label: "Attendance", href: "/dashboard/hr/attendance", icon: CalendarClock, section: "Attendance" },
    { label: "Work Hours Report", href: "/dashboard/admin/attendance-report", icon: Clock, section: "Attendance" },
    { label: "Profile Search", href: "/dashboard/profile-search", icon: Search, section: "Profiles" },
    { label: "Leave", href: "/dashboard/hr/leave", icon: ClipboardList, section: "HR Modules" },
    { label: "Recruitment", href: "/dashboard/hr/recruitment", icon: Users, section: "HR Modules" },
    { label: "Performance", href: "/dashboard/hr/performance", icon: Activity, section: "HR Modules" },
    { label: "Payroll", href: "/dashboard/hr/payroll", icon: CreditCard, section: "HR Modules" },
  ],
};
/**
 * One canonical nav destination per permission module, used to extend
 * a role's sidebar when an employee has been granted extra access to
 * that module via the Employee Access screen. Only modules that map
 * to an actual page are listed here — "Conversion" and
 * "ProfileCreation" don't have a distinct standalone page, so they're
 * intentionally omitted and won't add a sidebar item even if granted.
 */
export const EXTRA_ACCESS_NAV_ITEMS: { module: string; item: NavItem }[] = [
  { module: "Leads", item: { label: "Leads", href: "/dashboard/admin/leads", icon: Contact, section: "Profiles & Leads" } },
  { module: "Profiles", item: { label: "Profiles", href: "/dashboard/admin/profiles", icon: UserSquare2, section: "Profiles & Leads" } },
  { module: "Service", item: { label: "Service Overview", href: "/dashboard/admin/service-overview", icon: HeartHandshake, section: "Service" } },
  { module: "Employees", item: { label: "Employees", href: "/dashboard/admin/employees", icon: Users, section: "Employees" } },
  { module: "Settings", item: { label: "Settings", href: "/dashboard/admin/settings", icon: Settings, section: "Admin Tools" } },
  { module: "Payments", item: { label: "Payments", href: "/dashboard/admin/payments", icon: CreditCard, section: "Sales & Plans" } },
];
